x-airflow-common-env: &airflow-common-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  AIRFLOW__WEBSERVER__SECRET_KEY: "to_read_log_in_airflow_ui"
  PROJECT_PATH: ${PROJECT_PATH}


  GOOGLE_APPLICATION_CREDENTIALS: /opt/project/credentials/dw-healthcare-dbt.json
  BQ_DATASET: raw_api_dump
  GCP_PROJECT: dw-healthcare-dbt
  GCS_BUCKET: dw_healthcare_dbt_bucket


x-airflow-common-volumes: &airflow-common-volumes
  - ./dags:/opt/airflow/dags
  - .:/opt/project   
  - /var/run/docker.sock:/var/run/docker.sock
  - ./dw_healthcare:/opt/project/dw_healthcare
  - ./profiles.yml:/opt/project/profiles.yml



  

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.7.1
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: /bin/bash
    command:
      - -c
      - exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_ADMIN_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD:-admin}
      _AIRFLOW_WWW_USER_FIRSTNAME: ${AIRFLOW_ADMIN_FIRSTNAME:-Admin}
      _AIRFLOW_WWW_USER_LASTNAME: ${AIRFLOW_ADMIN_LASTNAME:-User}
      _AIRFLOW_WWW_USER_EMAIL: ${AIRFLOW_ADMIN_EMAIL:-admin@example.com}
    user: "0:0"
    volumes: *airflow-common-volumes

  airflow-webserver:
    image: apache/airflow:2.7.1
    command: webserver
    ports:
      - "8081:8080"
    environment:
      <<: *airflow-common-env
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: always
    volumes: *airflow-common-volumes

  airflow-scheduler:
    image: apache/airflow:2.7.1
    command: scheduler
    environment:
      <<: *airflow-common-env
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: always
    volumes: *airflow-common-volumes

  dbt:
    build: 
      context: .
      dockerfile: Dockerfile.dbt
    image: fazlan-dbt:1.5.0
    container_name: dbt
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /opt/project/credentials/dw-healthcare-dbt.json
    command: tail -f /dev/null
    volumes:
      - .:/opt/project 

volumes:
  postgres-data: